package com.sonique.domain.extension

import com.sonique.common.MERGING_DATA_TYPE
import com.sonique.domain.data.entities.SongEntity
import com.sonique.domain.data.model.browse.album.Track
import com.sonique.domain.data.model.cookie.CookieItem
import com.sonique.domain.data.player.GenericMediaItem
import com.sonique.domain.data.player.GenericMediaMetadata
import com.sonique.domain.utils.connectArtists
import com.sonique.domain.utils.isVideoThumbnailUrl
import com.sonique.domain.utils.toHighResThumbnailUrl
import com.sonique.domain.utils.toListName
import kotlinx.datetime.DateTimeUnit
import kotlinx.datetime.LocalDateTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.plus
import kotlinx.datetime.toInstant
import kotlinx.datetime.toLocalDateTime
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

@OptIn(ExperimentalTime::class)
fun now(): LocalDateTime = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())

fun LocalDateTime.isBefore(other: LocalDateTime): Boolean = this < other

fun LocalDateTime.isAfter(other: LocalDateTime): Boolean = this > other

@OptIn(ExperimentalTime::class)
fun LocalDateTime.plusSeconds(seconds: Long): LocalDateTime =
    this
        .toInstant(TimeZone.currentSystemDefault())
        .plus(seconds, DateTimeUnit.SECOND, TimeZone.currentSystemDefault())
        .toLocalDateTime(TimeZone.currentSystemDefault())

fun GenericMediaItem.isSong(): Boolean = this.metadata.description?.contains(MERGING_DATA_TYPE.SONG) == true

fun GenericMediaItem.isVideo(): Boolean = this.metadata.description?.contains(MERGING_DATA_TYPE.VIDEO) == true

fun GenericMediaItem.toSongEntity(): SongEntity =
    SongEntity(
        videoId = this.mediaId,
        albumId = null,
        albumName = this.metadata.albumTitle.toString(),
        artistId = null,
        artistName = listOf(this.metadata.artist.toString()),
        duration = "",
        durationSeconds = 0,
        isAvailable = true,
        isExplicit = false,
        likeStatus = "INDIFFERENT",
        thumbnails = this.metadata.artworkUri.toString(),
        title = this.metadata.title.toString(),
        videoType = "",
        category = "",
        resultType = "",
        liked = false,
        totalPlayTime = 0,
        downloadState = 0,
    )

fun SongEntity.toGenericMediaItem(): GenericMediaItem {
    val thumbUrl = this.thumbnails?.toHighResThumbnailUrl()
    val isSong = !com.sonique.domain.utils.isVideoThumbnailUrl(thumbUrl)
    return GenericMediaItem(
        mediaId = this.videoId,
        uri = this.videoId,
        metadata =
            GenericMediaMetadata(
                title = this.title,
                artist = this.artistName?.connectArtists(),
                albumTitle = this.albumName,
                artworkUri = thumbUrl,
                description = if (isSong) MERGING_DATA_TYPE.SONG else MERGING_DATA_TYPE.VIDEO,
            ),
        customCacheKey = this.videoId,
    )
}

fun Track.toGenericMediaItem(): GenericMediaItem {
    val rawThumb = this.thumbnails?.lastOrNull()?.url
        ?: "https://i.ytimg.com/vi/${this.videoId}/maxresdefault.jpg"
    val thumbUrl = rawThumb.toHighResThumbnailUrl()
    val artistName: String = this.artists.toListName().connectArtists()
    val isSong =
        (
            this.thumbnails?.lastOrNull()?.height != 0 &&
                this.thumbnails?.lastOrNull()?.height == this.thumbnails?.lastOrNull()?.width &&
                this.thumbnails?.lastOrNull()?.height != null
        ) && !isVideoThumbnailUrl(thumbUrl)
    return GenericMediaItem(
        mediaId = this.videoId,
        uri = this.videoId,
        metadata =
            GenericMediaMetadata(
                title = this.title,
                artist = artistName,
                albumTitle = this.album?.name,
                artworkUri = thumbUrl,
                description = if (isSong) MERGING_DATA_TYPE.SONG else MERGING_DATA_TYPE.VIDEO,
            ),
        customCacheKey = this.videoId,
    )
}

fun CookieItem.Content.toNetscapeFormat(includeSubdomains: Boolean = true): String {
    with(this) {
        val stringList =
            listOf(
                domain,
                includeSubdomains.toString().uppercase(),
                path,
                isSecure.toString().uppercase(),
                expiresUtc.toString(),
                name,
                value,
            )

        val builder = StringBuilder(stringList.first())

        for (s in stringList.subList(1, stringList.size)) {
            if (s.isNotEmpty()) {
                if (builder.isNotEmpty()) {
                    builder.append("\u0009")
                }
                builder.append(s)
            }
        }
        return builder.toString()
    }
}

fun CookieItem.toNetScapeString(): String =
    "# Netscape HTTP Cookie File\n" +
        "# WebView Generated by the Sonique com.sonique.app\n" +
        "# This is a generated file! Do not edit.\n\n" +
        this.content
            .fold(StringBuilder("")) { acc, cookie ->
                acc.append(cookie.toNetscapeFormat()).append("\n")
            }.toString()

